export default {
  CART_AMOUNT_INCREMENT: "CART_AMOUNT_INCREMENT",
  CART_AMOUNT_DECREMENT: "CART_AMOUNT_DECREMENT",
  CART_AMOUNT_DECREMENTASYNC: "CART_AMOUNT_DECREMENTASYNC",
  START_FETCH_BLOG_LIST: "START_FETCH_BLOG_LIST",
  FETCH_BLOG_LIST_SUCCESS: "FETCH_BLOG_LIST_SUCCESS",
  FETCH_BLOG_LIST_FAILED: "FETCH_BLOG_LIST_FAILED"
};
